// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqdBz_duKTfCHkCzIukTciqxncj46xgwk',
    appId: '1:43583467539:web:1ae313b457597bee8f0fe6',
    messagingSenderId: '43583467539',
    projectId: 'zoom-clone-a067d',
    authDomain: 'zoom-clone-a067d.firebaseapp.com',
    storageBucket: 'zoom-clone-a067d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCunvP2ljdT1IkWnOxP-IEWF9J2LgBdtiM',
    appId: '1:43583467539:android:fae5339ae16b03d88f0fe6',
    messagingSenderId: '43583467539',
    projectId: 'zoom-clone-a067d',
    storageBucket: 'zoom-clone-a067d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs_61i_4GwVfm8or1-l8Tv3dVm34TOt74',
    appId: '1:43583467539:ios:05f0fb773f05cb388f0fe6',
    messagingSenderId: '43583467539',
    projectId: 'zoom-clone-a067d',
    storageBucket: 'zoom-clone-a067d.firebasestorage.app',
    iosBundleId: 'com.example.zoomClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs_61i_4GwVfm8or1-l8Tv3dVm34TOt74',
    appId: '1:43583467539:ios:05f0fb773f05cb388f0fe6',
    messagingSenderId: '43583467539',
    projectId: 'zoom-clone-a067d',
    storageBucket: 'zoom-clone-a067d.firebasestorage.app',
    iosBundleId: 'com.example.zoomClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqdBz_duKTfCHkCzIukTciqxncj46xgwk',
    appId: '1:43583467539:web:8294369f532e3b328f0fe6',
    messagingSenderId: '43583467539',
    projectId: 'zoom-clone-a067d',
    authDomain: 'zoom-clone-a067d.firebaseapp.com',
    storageBucket: 'zoom-clone-a067d.firebasestorage.app',
  );
}
